# Generated by Django 5.2.4 on 2025-07-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_meal_dailymenu_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="mpesa_checkout_request_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="mpesa_merchant_request_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="mpesa_receipt_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payer_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="transaction_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
